using System;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace APIGateWay.ModalLayer.ChatsModal.Master
{
    /// <summary>
    /// An end-to-end encrypted message. The server stores only ciphertext; the content
    /// key needed to decrypt it is wrapped per recipient user in <see cref="ChatMessageKey"/>.
    /// </summary>
    [Table("ChatEncryptedMessages")]
    public class ChatEncryptedMessage
    {
        [Key]
        public Guid Id { get; set; }
        public Guid ConversationId { get; set; }
        public Guid SenderUserId { get; set; }

        /// <summary>Generated by the sender; unique per sender so retries are idempotent.</summary>
        public string ClientMessageId { get; set; } = string.Empty;

        /// <summary>[12-byte IV | AES-256-GCM ciphertext + tag]</summary>
        public byte[] EncryptedPayload { get; set; } = Array.Empty<byte>();

        public Guid? ReplyToMessageId { get; set; }

        [Column(TypeName = "datetime2")]
        public DateTime CreatedAt { get; set; }
    }

    /// <summary>
    /// The message content key wrapped for one recipient user (the sender gets a row too).
    /// Composite key (MessageId, RecipientUserId) — configured in APIGatewayDBContext.
    /// </summary>
    [Table("ChatMessageKeys")]
    public class ChatMessageKey
    {
        public Guid MessageId { get; set; }
        public Guid RecipientUserId { get; set; }
        public byte[] WrappedMessageKey { get; set; } = Array.Empty<byte>();
    }
}
