using System;
using System.Collections.Generic;
using Microsoft.AspNetCore.Http;

namespace APIGateWay.ModalLayer.ChatsModal.DTOs
{
    // All binary fields travel as base64 strings.

    /// <summary>POST /api/Chats/direct</summary>
    public class OpenDirectConversationDto
    {
        public Guid UserId { get; set; }
    }

    /// <summary>POST /api/Chats/group</summary>
    public class CreateGroupConversationDto
    {
        public string Title { get; set; } = string.Empty;

        /// <summary>Other members to add alongside the caller (who is always added as Admin).</summary>
        public List<Guid> MemberUserIds { get; set; } = new();
    }

    /// <summary>POST /api/Chats/{conversationId}/members — Admin only.</summary>
    public class ManageGroupMembersDto
    {
        public List<Guid> AddUserIds { get; set; } = new();
        public List<Guid> RemoveUserIds { get; set; } = new();
    }

    /// <summary>POST /api/Chats/{conversationId}/icon — Admin only, multipart/form-data.</summary>
    public class UploadGroupIconDto
    {
        public IFormFile Icon { get; set; } = null!;
    }

    public class ConversationDto
    {
        public Guid ConversationId { get; set; }

        /// <summary>1 = Direct, 2 = Group</summary>
        public int Type { get; set; }
        public string? Title { get; set; }

        /// <summary>Group photo URL; null for Direct conversations and groups without one set.</summary>
        public string? GroupIconUrl { get; set; }
        public List<Guid> MemberUserIds { get; set; } = new();

        /// <summary>Admin | Member per member; group conversations only (empty for Direct).</summary>
        public Dictionary<Guid, string> MemberRoles { get; set; } = new();
        public DateTime CreatedAt { get; set; }
        public DateTime? LastMessageAt { get; set; }

        /// <summary>The caller's read marker.</summary>
        public DateTime? LastReadAt { get; set; }

        /// <summary>Messages from other members newer than LastReadAt.</summary>
        public int UnreadCount { get; set; }

        /// <summary>Newest message, with the caller's wrapped key, so the list can show a decrypted preview.</summary>
        public ChatMessageDto? LastMessage { get; set; }
    }

    /// <summary>The message content key wrapped for one member (the sender included).</summary>
    public class MessageRecipientKeyDto
    {
        public Guid RecipientUserId { get; set; }
        public string WrappedMessageKey { get; set; } = string.Empty;
    }

    /// <summary>POST /api/Chats/{conversationId}/messages</summary>
    public class SendMessageDto
    {
        /// <summary>Generated by the sender and used as the message id (it is also the HKDF salt).</summary>
        public Guid ClientMessageId { get; set; }

        /// <summary>[12-byte IV | AES-256-GCM ciphertext + tag]</summary>
        public string EncryptedPayload { get; set; } = string.Empty;

        /// <summary>Exactly one entry per conversation member, sender included.</summary>
        public List<MessageRecipientKeyDto> Keys { get; set; } = new();

        /// <summary>Message this is a threaded reply to; must belong to the same conversation.</summary>
        public Guid? ReplyToMessageId { get; set; }

        /// <summary>@user / #ticket / #meeting / #project / #repo references found in the message text.
        /// The token itself stays inside EncryptedPayload; only this metadata is sent in the clear.</summary>
        public List<MessageTagDto> Tags { get; set; } = new();
    }

    /// <summary>Unencrypted reference from a message to a WGNest entity. EntityType is one of
    /// User | Ticket | Meeting | Project | Repo (see ChatTagEntityType).</summary>
    public class MessageTagDto
    {
        public string EntityType { get; set; } = string.Empty;
        public string EntityId { get; set; } = string.Empty;
        public string DisplayText { get; set; } = string.Empty;

        /// <summary>Optional — the user to alert (e.g. a ticket's assignee). Not persisted; used only
        /// to fan out the realtime "ChatMention" event. Ignored for EntityType = User (the tagged user
        /// themselves, parsed from EntityId, is always notified).</summary>
        public Guid? NotifyUserId { get; set; }
    }

    public class ChatMessageDto
    {
        public Guid MessageId { get; set; }
        public Guid ConversationId { get; set; }
        public Guid SenderUserId { get; set; }
        public string ClientMessageId { get; set; } = string.Empty;
        public string EncryptedPayload { get; set; } = string.Empty;
        public Guid? ReplyToMessageId { get; set; }
        public DateTime CreatedAt { get; set; }

        /// <summary>The content key wrapped for the receiving user only; null if they have no key row.</summary>
        public string? WrappedMessageKey { get; set; }

        /// <summary>Unencrypted — who reacted with which emoji. Not confidential message content.</summary>
        public List<MessageReactionDto> Reactions { get; set; } = new();

        /// <summary>Unencrypted — @user / #ticket / #meeting / #project / #repo references. Not confidential message content.</summary>
        public List<MessageTagDto> Tags { get; set; } = new();

        /// <summary>Present only for a media/voice-note message. The file itself is fetched separately
        /// from GET /api/Chats/media/{MediaId} and decrypted client-side.</summary>
        public MediaAttachmentDto? Media { get; set; }
    }

    /// <summary>
    /// POST /api/Chats/{conversationId}/media — multipart/form-data. Same envelope as a text send
    /// (EncryptedPayload/Keys/ReplyToMessageId/Tags), plus the encrypted file itself. The file's random
    /// AES-256-GCM key is wrapped with the message's own content key (WebCrypto wrapKey, AES-GCM), so
    /// only conversation members can ever unwrap it — the server never sees an unwrapped file key.
    /// ChatMediaAttachments.Id is always set to ClientMessageId (one attachment per message in this design).
    /// </summary>
    public class SendMediaMessageDto
    {
        public Guid ClientMessageId { get; set; }
        public string EncryptedPayload { get; set; } = string.Empty;
        public List<MessageRecipientKeyDto> Keys { get; set; } = new();
        public Guid? ReplyToMessageId { get; set; }
        public List<MessageTagDto> Tags { get; set; } = new();

        /// <summary>[12-byte wrap IV | AES-GCM-wrapped 32-byte file key + 16-byte tag] = 60 bytes, base64.</summary>
        public string EncryptedFileKey { get; set; } = string.Empty;

        /// <summary>12-byte AES-GCM nonce used to encrypt the file bytes themselves, base64.</summary>
        public string Iv { get; set; } = string.Empty;
        public string OriginalFileName { get; set; } = string.Empty;
        public string MimeType { get; set; } = string.Empty;

        /// <summary>The encrypted file bytes (ciphertext + GCM tag) — opaque to the server.</summary>
        public IFormFile File { get; set; } = null!;
    }

    public class MediaAttachmentDto
    {
        public Guid MediaId { get; set; }
        public string OriginalFileName { get; set; } = string.Empty;
        public string MimeType { get; set; } = string.Empty;
        public long FileSize { get; set; }
        public string EncryptedFileKey { get; set; } = string.Empty;
        public string Iv { get; set; } = string.Empty;
    }

    /// <summary>Payload of the "ChatMention" realtime event, sent to a tagged/notified user's own user-{id} group.</summary>
    public class ChatMentionEventDto
    {
        public Guid ConversationId { get; set; }
        public Guid MessageId { get; set; }
        public Guid TaggedByUserId { get; set; }
        public string EntityType { get; set; } = string.Empty;
        public string EntityId { get; set; } = string.Empty;
        public string DisplayText { get; set; } = string.Empty;
    }

    /// <summary>POST /api/Chats/messages/{messageId}/reactions — toggles the caller's reaction.</summary>
    public class ToggleReactionDto
    {
        public string Emoji { get; set; } = string.Empty;
    }

    public class MessageReactionDto
    {
        public Guid UserId { get; set; }
        public string Emoji { get; set; } = string.Empty;
    }

    /// <summary>Response of the toggle endpoint and payload of the "MessageReactionChanged" realtime event.</summary>
    public class MessageReactionEventDto
    {
        public Guid MessageId { get; set; }
        public Guid ConversationId { get; set; }
        public Guid UserId { get; set; }
        public string Emoji { get; set; } = string.Empty;

        /// <summary>true = reaction was added, false = the user's existing reaction was removed.</summary>
        public bool Added { get; set; }
    }

    /// <summary>POST /api/Chats/{conversationId}/read</summary>
    public class MarkConversationReadDto
    {
        /// <summary>CreatedAt of the newest message the client displayed; null = now.</summary>
        public DateTime? ReadUpTo { get; set; }
    }

    /// <summary>Response of the read endpoint and payload of the "ChatRead" realtime event.</summary>
    public class ConversationReadDto
    {
        public Guid ConversationId { get; set; }
        public DateTime? LastReadAt { get; set; }
    }
}
